/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:btnRight:481471:
  println("btnRight - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("d");
} //_CODE_:btnRight:481471:

public void button2_click1(GButton source, GEvent event) { //_CODE_:btnUp:317093:
  println("btnUp - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("w");
} //_CODE_:btnUp:317093:

public void button3_click1(GButton source, GEvent event) { //_CODE_:btnLeft:956673:
  println("btnLeft - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("a");
} //_CODE_:btnLeft:956673:

public void button4_click1(GButton source, GEvent event) { //_CODE_:btnDown:987894:
  println("btnDown - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("s");
} //_CODE_:btnDown:987894:

public void button1_click2(GButton source, GEvent event) { //_CODE_:btnStop:632732:
  println("btnStop - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("o");
} //_CODE_:btnStop:632732:

public void button1_click3(GButton source, GEvent event) { //_CODE_:btntask2:442839:
  println("btntask2 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("t");
} //_CODE_:btntask2:442839:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:txtAreaMessage:713942:
  println("txtAreaMessage - GTextArea >> GEvent." + event + " @ " + millis());
  //String text = myPort.readStringuntil();
  //txtAreaMessage.setText(text);
  //txtAreaMessage.
} //_CODE_:txtAreaMessage:713942:

public void button2_click2(GButton source, GEvent event) { //_CODE_:btnscanRoom:664862:
  println("btnscanRoom - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("r");
} //_CODE_:btnscanRoom:664862:

public void button1_click4(GButton source, GEvent event) { //_CODE_:btncomplete:898717:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("c");
} //_CODE_:btncomplete:898717:

public void button2_click3(GButton source, GEvent event) { //_CODE_:btnrightRoom:814781:
  println("btnrightRoom - GButton >> GEvent." + event + " @ " + millis());
  myPort.write(">");
} //_CODE_:btnrightRoom:814781:

public void button3_click2(GButton source, GEvent event) { //_CODE_:btnleftRoom:713857:
  println("btnleftRoom - GButton >> GEvent." + event + " @ " + millis());
  myPort.write("<");
} //_CODE_:btnleftRoom:713857:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:txtField:419855:
  println("txtField - GTextField >> GEvent." + event + " @ " + millis());
  
} //_CODE_:txtField:419855:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  btnRight = new GButton(this, 188, 105, 80, 30);
  btnRight.setText("RIGHT");
  btnRight.addEventHandler(this, "button1_click1");
  btnUp = new GButton(this, 98, 64, 80, 30);
  btnUp.setText("UP");
  btnUp.addEventHandler(this, "button2_click1");
  btnLeft = new GButton(this, 4, 106, 80, 30);
  btnLeft.setText("LEFT");
  btnLeft.addEventHandler(this, "button3_click1");
  btnDown = new GButton(this, 94, 148, 80, 30);
  btnDown.setText("DOWN");
  btnDown.addEventHandler(this, "button4_click1");
  btnStop = new GButton(this, 96, 106, 80, 30);
  btnStop.setText("STOP");
  btnStop.addEventHandler(this, "button1_click2");
  btntask2 = new GButton(this, 410, 144, 80, 30);
  btntask2.setText("TASK 2");
  btntask2.addEventHandler(this, "button1_click3");
  txtAreaMessage = new GTextArea(this, 10, 201, 259, 130, G4P.SCROLLBARS_VERTICAL_ONLY);
  txtAreaMessage.setOpaque(true);
  txtAreaMessage.addEventHandler(this, "textarea1_change1");
  btnscanRoom = new GButton(this, 409, 102, 80, 30);
  btnscanRoom.setText("SCAN ROOM");
  btnscanRoom.addEventHandler(this, "button2_click2");
  btncomplete = new GButton(this, 411, 60, 80, 30);
  btncomplete.setText("COMPLETE");
  btncomplete.addEventHandler(this, "button1_click4");
  btnrightRoom = new GButton(this, 500, 101, 80, 30);
  btnrightRoom.setText("RIGHT MOVE");
  btnrightRoom.addEventHandler(this, "button2_click3");
  btnleftRoom = new GButton(this, 319, 101, 80, 30);
  btnleftRoom.setText("LEFT ROOM");
  btnleftRoom.addEventHandler(this, "button3_click2");
  txtField = new GTextField(this, 328, 201, 238, 99, G4P.SCROLLBARS_NONE);
  txtField.setOpaque(true);
  txtField.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 18, 25, 171, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("WASD CONTROLS");
  label1.setOpaque(false);
  label2 = new GLabel(this, 335, 25, 248, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("ROOM AND CORRIDOR BUTTONS");
  label2.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton btnRight; 
GButton btnUp; 
GButton btnLeft; 
GButton btnDown; 
GButton btnStop; 
GButton btntask2; 
GTextArea txtAreaMessage; 
GButton btnscanRoom; 
GButton btncomplete; 
GButton btnrightRoom; 
GButton btnleftRoom; 
GTextField txtField; 
GLabel label1; 
GLabel label2; 